# Generated by Django 3.2.7 on 2021-12-13 13:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Username')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('password', models.CharField(max_length=100, verbose_name='Password')),
                ('name', models.CharField(default='', max_length=60, verbose_name='name')),
                ('lastName', models.CharField(max_length=60, null=True)),
                ('birthDate', models.DateField(default=datetime.datetime.now)),
                ('gender', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('O', 'Otro')], max_length=40, null=True)),
                ('documentNumber', models.CharField(max_length=20, null=True)),
                ('phoneNumber', models.CharField(max_length=60, null=True)),
                ('typeAccount', models.CharField(choices=[('D', 'Driver'), ('P', 'Passenger')], max_length=60, verbose_name='Type Account')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('carRegistrationNumber', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('licenseNumber', models.CharField(max_length=20, null=True)),
                ('color', models.CharField(max_length=60)),
                ('brand', models.CharField(max_length=60)),
                ('model', models.CharField(max_length=60)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('equipament', models.CharField(choices=[('PU', 'Pick Up'), ('T', 'Con Trunk'), ('NT', 'Sin Trunk')], max_length=40)),
                ('userFK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_car', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
