# Generated by Django 3.2.7 on 2021-12-04 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_auto_20211204_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('licenseNumber', models.CharField(max_length=20, null=True)),
                ('carRegistrationNumber', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=60)),
                ('brand', models.CharField(max_length=60)),
                ('model', models.CharField(max_length=60)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('equipament', models.CharField(choices=[('PU', 'Pick Up'), ('T', 'Con Trunk'), ('NT', 'Sin Trunk')], max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
